cuda_device: True

data:
  data_bucket: '/gong-hmi'
  data_folder: 'to-ml-temp-gong'
#  index_range: [0, 3200]
  normalisation: 3500.0

net: 
  name:  'HighResNet_RPRCDO'
  upscale_factor: 4
  n_frames: 1
  p: 0.0

loss:
  name: 'SSIMGradHistLoss'
  dl: 0.15
  noise_level: 60
  lim: 5000
  coeff_hist: 0.000001
  coeff_ssim: 0.0005
  coeff_grad: 5

learning_rate: 0.0001
beta1: 0.5
batch_size: 128
is_gradient: True
nepochs: 20
comment: 'SSIMGradHistLoss_gong'


